# Generated by Django 6.1.1 on 2026-09-22 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('model_provider', models.CharField(default='gemini', editable=False, max_length=32)),
                ('model_id', models.CharField(max_length=64)),
                ('quick_model_id', models.CharField(max_length=64)),
                ('lyria_model_id', models.CharField(max_length=64)),
                ('model_api_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserKeyBind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserConfig.modelkey')),
                ('user', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
