# Generated by Django 6.0.1 on 2026-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelkey',
            name='model_id',
            field=models.CharField(default='gemini-3-pro-preview', max_length=64),
        ),
    ]
