# Generated by Django 6.0.1 on 2026-01-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserConfig', '0002_modelkey_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelkey',
            name='quick_model_id',
            field=models.CharField(default='models/gemini-3-flash-preview', max_length=64),
        ),
    ]
