# Generated by Django 6.1.1 on 2026-09-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Conversation', '0003_image_delete_diagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.BinaryField()),
                ('prompt', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='Conversation.conversation')),
            ],
        ),
    ]
