# Generated by Django 6.1.1 on 2026-09-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioGeneration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
