# Generated by Django 6.1.1 on 2026-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioGeneration', '0002_music_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='mime_type',
            field=models.TextField(blank=True),
        ),
    ]
