# Generated by Django 6.1.1 on 2026-09-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='function_call',
        ),
    ]
