# Generated by Django 6.0.1 on 2026-01-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0002_conversation_title_alter_diagram_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='model_provider',
        ),
    ]
