# Generated by Django 6.0.1 on 2026-01-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0003_remove_conversation_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='profile',
            field=models.TextField(blank=True),
        ),
    ]
