# Generated by Django 6.0.1 on 2026-01-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0004_diagram_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('S', 'system'), ('U', 'user'), ('M', 'model'), ('T', 'tool')], max_length=1),
        ),
    ]
