# Generated by Django 6.0.1 on 2026-01-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0005_alter_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='syntax',
            field=models.CharField(choices=[('MER', 'mermaid'), ('CYT', 'cytoscape')], default='MER', max_length=3),
        ),
    ]
