# Generated by Django 6.0.1 on 2026-01-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0006_diagram_syntax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='syntax',
            field=models.CharField(choices=[('MER', 'mermaid'), ('CYT', 'cytoscape'), ('GVZ', 'graphviz')], default='MER', max_length=3),
        ),
    ]
