# Generated by Django 6.0.1 on 2026-01-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0007_alter_diagram_syntax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='modified_time',
        ),
    ]
