# Generated by Django 6.0.1 on 2026-01-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0008_remove_conversation_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='syntax',
            field=models.CharField(choices=[('MER', 'mermaid'), ('CYT', 'cytoscape'), ('GVZ', 'graphviz'), ('TIK', 'tikz')], default='MER', max_length=3),
        ),
    ]
