# Generated by Django 6.0.1 on 2026-01-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0009_alter_diagram_syntax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='syntax',
            field=models.CharField(choices=[('MER', 'mermaid'), ('CYT', 'cytoscape'), ('GVZ', 'graphviz'), ('TIK', 'tikz'), ('DRI', 'drawio')], default='MER', max_length=3),
        ),
    ]
