# Generated by Django 6.0.1 on 2026-02-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0010_alter_diagram_syntax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='syntax',
            field=models.CharField(choices=[('MER', 'mermaid'), ('CYT', 'cytoscape'), ('GVZ', 'graphviz'), ('TIK', 'tikz'), ('DRI', 'drawio'), ('SVG', 'svg')], default='MER', max_length=3),
        ),
    ]
